### ISSUE TITLE
Leaflet map with points sized by location or ? 

### ISSUE THREAD

**Issue by softloud** [ESHackathon/eviatlas#1]

**Comment by softloud** [comment]
Great tips in [this](https://www.r-bloggers.com/4-tricks-for-working-with-r-leaflet-and-shiny/) post, thanks @afeierman.

I like the way they display the info in a side panel rather than a popup.

**Comment by afeierman** [comment]
working on this now-- sizing points based on whatever numeric columns are in the data that they upload
