### ISSUE TITLE
Heatmap does not display for certain columns

### ISSUE THREAD

**Issue by afeierman** [ESHackathon/eviatlas#12]
This is a bug, but may be an accidental feature in some ways (e.g. you don't always want to create a heatmap for certain variables)

@sonia, who is not on this repo

**Comment by afeierman** [comment]
one solution for this: in the `GenHeatMap` UI, only display columns that have a certain low number of unique values (maybe the square root of the total number of rows, or just pick an arbitrary number like 50)

**Comment by cicatrixx** [comment]
I think we did apply some filter to make sure not all columns can be used
for the heat map. Can you specify which dataset add column is having  the
issue? I can take a look.

**Comment by afeierman** [comment]
yea @cicatrixx that's absolutely right-- If i recall correctly, as implemented the function looks for columns that have a low number of unique entries and columns to build the initial plots off based on that search. I was thinking that columns that will almost always be unique, like Title or DOI, shouldn't be available for the user to select

**Comment by afeierman** [comment]
helper function added to control this in 67c8621387a4b005c885439e19cc9d318db27418.
