### ISSUE TITLE
allow filtering for multiple categories, and button to clear active filters

### ISSUE THREAD

**Issue by afeierman** [ESHackathon/eviatlas#18]
Building on what @mjwestgate wrote for commit 8f1eb7d49f02cc7e4f2da149aff562bf131f9c28

**Comment by afeierman** [comment]
update-- through functionality in the DT package, you can now filter for any column in the View Data tab. But, this filtering functionality doesn't change the `data_internal$filtered` variable that's passed through the app. this can still be fixed/improved with a filtering solution that propagates through the app

**Comment by mjwestgate** [comment]
This DT::datatable solution is actually really neat - I haven't seen this before! We can look at propagating data filters later on, but there might be reasons you don't want to do that. So maybe filtering should be done independently for each tab? I'm not sure what's best here, so I'm happy to stick with this solution for now.

**Comment by afeierman** [comment]
sounds good to me. sweet!
