### ISSUE TITLE
wrangle multiple fields in one column in SR 6 & SR 9

### ISSUE THREAD

**Issue by softloud** [ESHackathon/eviatlas#22]

**Comment by DrMattG** [comment]
Is it best to do this by splitting the string and then duplicating the row?

**Comment by DrMattG** [comment]
Would this work? (using SR6 dataset)
SR6<-SR6 %>% 
  mutate(`Forest type` = strsplit(as.character(`Forest type`), ";")) %>% 
  unnest(`Forest type`)
