### ISSUE TITLE
Plot shapefiles

### ISSUE THREAD

**Issue by DrMattG** [ESHackathon/eviatlas#6]

**Comment by afeierman** [comment]
@DrMattG did the legwork to get this started at ESHack2019--Remote, and it's now starting to take shape in f6c3f7990f2731187e9e8fe3facaa6a6697f3d46 on branch upload_shapefile. Currently, app can upload a shapefile and display it on a map. However, pop-ups and other graphs aren't yet functional yet. 

Shapefile is read in by `sf`, and the resulting object functions much like a tibble or data.frame, so incorporating functionality should be relatively straightforward from here

**Comment by afeierman** [comment]
getting close to release-worthy status with d8b6911

**Comment by afeierman** [comment]
Functions, with limited support, as of v0.3 and commit 6ea1bce038a771f7f1384b8d8bd7ab7025470e50. Nice work @DrMattG! Feels good to knock off an issue we raised on day 1 of this project a year and a half ago.
