### ISSUE TITLE
Officially archive this repository

### ISSUE THREAD

**Issue by afeierman** [ESHackathon/eviatlas#67]
We should officially archive this in the repository settings on Github now that development is happening at https://github.com/rmetaverse/eviatlas, but you need administrator rights to do so. I'm not sure who has them on this repo, maybe @nealhaddaway or @softloud?

**Comment by mjwestgate** [comment]
No worries Andrew - I've made you an admin - will do the same on the metaverse version if I haven't already

**Comment by afeierman** [comment]
Great, will archive now!
