### ISSUE TITLE
Missing tiles when zoomed in on html output ESRI worldmap basemap

### ISSUE THREAD

**Issue by DrMattG** [ESHackathon/eviatlas#97]

**Comment by DrMattG** [comment]
I think this might be an ESRI problem - I tried updating leaflet.providers but that doesnt seem to help 

There is this: https://stackoverflow.com/questions/44096533/esri-leaflet-missing-tiles
and this: https://github.com/Esri/esri-leaflet-vector/issues/55

Maybe a solution: https://stackoverflow.com/questions/43046753/r-leaflet-offline-tiles-within-shiny but a real pain in the arse

**Comment by nealhaddaway** [comment]
Urgh - is there an alternative base map we could use instead?
________________________________

**Comment by nealhaddaway** [comment]
God - how do we choose? SO MANY!
________________________________

**Comment by DrMattG** [comment]
I think we should leave the option for ESRI in but perhaps add documentation (that no one will read) to say this is an issue. I say this because in some circumstances the map tiles work (if you dont zoom in to much or in the "right" spot)

**Comment by nealhaddaway** [comment]
Ah - I think Jacqui and I may see something different - grey tiles are all over the place for me...

**Comment by DrMattG** [comment]
That's weird! Why the difference do you think (has Norway payed the bill and the UK not??) :)

**Comment by DrMattG** [comment]
So for me the level of zoom makes the difference - for example lookiing at Europe I can make an image with no missing tiles (in the html saved map) but if I zoom in a little bit I get some missing tiles. This is not consistent across the map or across the zoom scale.
![image](https://user-images.githubusercontent.com/11541781/167404923-87d4236e-3e55-4f80-a840-7e7fe361eba3.png)
![image](https://user-images.githubusercontent.com/11541781/167404972-22b9acf4-cb2c-44e4-8d25-6295dcbd0b5d.png)

**Comment by DrMattG** [comment]
Can we close this @nealhaddaway - It seems to be working now

**Comment by nealhaddaway** [comment]
Urgh… maybe we can just replace ESRI with something else?

Sent from my iPhone

On 26 May 2022, at 21:28, Matthew Grainger ***@***.***> wrote:

﻿

Can we close this @nealhaddaway<https://github.com/nealhaddaway> - It seems to be working now
